name: Build Image

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta for kubesphere
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            kubespheredev/ks-jenkins
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: maven
          restore-keys: maven
      - name: Dependency
        run: |
          wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
          tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
          ls -ahl
      - name: Build
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{secrets.DOCKER_HUB_TOKEN}}

          mkdir -p ~/.m2
          echo "${{secrets.MVN_SETTINGS}}" > ~/.m2/settings.xml
          curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv
          export PATH=.:$PATH:phantomjs/bin
          jcli cwp --install-artifacts --config-path formula.yaml \
            --value-set version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

          # there's no a release for the multi-arch building but https://github.com/jenkinsci/custom-war-packager/releases/tag/v2.0-alpha-6
          wget https://github.com/LinuxSuRen/custom-war-packager/releases/download/v2.0-alpha-6/custom-war-packager-cli-2.0-alpha-7-20210527.031403-1-jar-with-dependencies.jar
          mv custom-war-packager-cli-2.0-alpha-7-20210527.031403-1-jar-with-dependencies.jar ~/.jenkins-cli/cwp-cli.jar
          jcli cwp --install-artifacts --config-path formula-arm.yaml --value-set output=push \
            --value-set version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      - name: Push Image
        run: |
          version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          docker push kubespheredev/ks-jenkins:{{.version}}-2.249.1
